import requests
import json

def ask_ollama_scientist(chemical_name, formula, iupac_name):
    print(f"\n🧠 Sending data to Ollama (Llama 3) for Medical Reasoning...")
    
    url = "http://localhost:11434/api/generate"
    
    # Prompting the LLM to act as a Bio-Chemist
    prompt = f"""
    You are an expert Bio-Chemist and Drug Discovery Scientist.
    Analyze the following phytochemical data and provide a brief medical reasoning report:
    
    Chemical Name: {chemical_name}
    Molecular Formula: {formula}
    IUPAC Name: {iupac_name}
    
    Please provide:
    1. Primary potential medical benefits.
    2. How it interacts with the human body (Mechanism of Action) in simple terms.
    """
    
    payload = {
        "model": "llama3",
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(url, json=payload)
        if response.status_code == 200:
            result = response.json()
            print("\n🔬 --- SCIENTIFIC REPORT GENERATED BY OLLAMA --- 🔬")
            print(result.get("response"))
        else:
            print(f"❌ Ollama Error. Status Code: {response.status_code}")
    except Exception as e:
        print(f"⚠️ Could not connect to Ollama: {e}. Is Ollama running in the background?")

# Dummy data from our previous step to test Ollama
ask_ollama_scientist("Curcumin", "C21H20O6", "(1E,6E)-1,7-bis(4-hydroxy-3-methoxyphenyl)hepta-1,6-diene-3,5-dione")